Scaler
GenXProject/GenX.jl pull request #667
Opened 2024-03-25 04:55 UTC by Betristor

## Description

Sometimes the model will be built into an ill form if some objective terms are quite large or small. To alleviate this problem, we could add a scaling factor to scale the objective function during solving while leaving all other expressions untouched. In example_systems/1_three_zones case, an example ObjScale of 10 could help to change the objective range from [1e-4, 6e+02] to [1e-3, 6e+03].

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [ ] Code Refactor
- [x] Performance Improvements

## Related Tickets & Documents

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [x] The latest changes on the target branch have been incorporated, so that any conflicts are taken care of before merging. This can be accomplished either by merging in the target branch (e.g. 'git merge develop') or by rebasing on top of the target branch (e.g. 'git rebase develop'). Please do not hesitate to reach out to the GenX development team if you need help with this.
- [x] Code has been tested to ensure all functionality works as intended.
- [x] CHANGELOG.md has been updated (if this is a 'notable' change).
- [x] I consent to the release of this PR's code under the GNU General Public license.

## How this can be tested
Add the setting key ```ObjScale``` with an appropriate value to ```genx_settings.yml``` in any test cases. The objective function will be scaled accordingly.

## Post-approval checklist for GenX core developers
After the PR is approved

- [ ] Check that the latest changes on the target branch are incorporated, either via merge or rebase
- [ ] Remember to squash and merge if incorporating into develop

2024-03-27 15:57 UTC, sambuddhac requested changes
Can you please mention a concrete example in which the ObjScale is something other than 1? I am failing to understand where exactly the current code-base is having problem? We already have a ParameterScale as @JesseJenkins mentioned in his response to the associated issue. In this PR you have kept the scaling factor to 1 and yet you mentioned in the description that the objective needs to be scaled. So, I am unable to understand. Have you tried using the ParameterScale that's already there in GenX?

2024-03-30 05:32 UTC, Betristor commented
@sambuddhac Yes, I have considered ```ParameterScale``` setting but this option will scale nearly all the data and parameters we use during the model construction and sequentially influence the outputs since the physical meaning (units) of outputs are scaled. Indeed this ```ParameterScale``` setting could help alleviate possible numerical issues in the model, but we still need to face the inconvenience of additional loading burden and output interpretation. While ```ObjScale``` operates at a higher level by scaling the objective expression directly, avoiding manipulating inputs and outputs. 
As for an example, example_systems/2_three_zones_w_electrolyzer case with a ```ObjScale``` value of 100 could help to change the objective range from [6e-07, 7e+02] to [6e-03, 7e+04] (similar to example_systems/1_three_zones case mentioned above). But I left the key default as 1 to have examples unchanged.

2024-04-02 20:20 UTC, sambuddhac commented
@nspatank I am assigning this to in order to respond.

2024-04-03 15:48 UTC, sambuddhac approved these changes

2024-04-03 16:20 UTC, merged