Update retrofits.jl documentation with additional text
GenXProject/GenX.jl pull request #730
Opened 2024-07-30 19:18 UTC by sambuddhac

Text added in boldface "and efficiency 𝑒𝑓𝑟 is a scalar multiplier that denotes an 'exchange rate' between capacity of the original resource and any retrofit technologies (e.g. how many MW of resource B can be sited per MW of resource A retired)." to the documentation page for retrofits

## Description

Please do not leave this blank 
This PR adds the following text at the end of the documentation page for retrofits in boldface: and efficiency 𝑒𝑓𝑟 is a scalar multiplier that denotes an 'exchange rate' between capacity of the original resource and any retrofit technologies (e.g. how many MW of resource B can be sited per MW of resource A retired).

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Bug Fix
- [x] Documentation Update
- [ ] Code Refactor
- [ ] Performance Improvements

## Related Tickets & Documents

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [x] The latest changes on the target branch have been incorporated, so that any conflicts are taken care of before merging. This can be accomplished either by merging in the target branch (e.g. 'git merge develop') or by rebasing on top of the target branch (e.g. 'git rebase develop'). Please do not hesitate to reach out to the GenX development team if you need help with this.
- [x] Code has been tested to ensure all functionality works as intended.
- [x] CHANGELOG.md has been updated (if this is a 'notable' change).
- [x] I consent to the release of this PR's code under the GNU General Public license.

## How this can be tested

## Post-approval checklist for GenX core developers
After the PR is approved

- [ ] Check that the latest changes on the target branch are incorporated, either via merge or rebase
- [ ] Remember to squash and merge if incorporating into develop

2024-08-12 14:24 UTC, JesseJenkins requested changes
Remove boldface formating.

2024-08-12 15:10 UTC, sambuddhac commented
I think now, this should be ready to go, @JesseJenkins

2024-08-19 20:37 UTC, lbonaldo approved these changes

2024-08-20 00:32 UTC, JesseJenkins approved these changes

2024-08-20 01:31 UTC, merged