Additional constraints to prevent violation of state of charge limits in non-representative periods
GenXProject/GenX.jl pull request #781
Opened 2024-10-07 21:04 UTC by federicoparolin

## Description

- Introduced additional constraints to bound the state of charge of LDS systems within the limits (zero and installed energy capacity) throughout the entire time horizon (as described in https://doi.org/10.48550/arXiv.2409.19079).
- Saving of storage content evolution throughout the entire time horizon (StorageEvol.csv and HSC_StorageEvol.csv)

Storage content evolution over full time horizon with the original (a) and updated (b) formulations:
![immagine](https://github.com/user-attachments/assets/0e2df005-3099-4d56-a217-2cb38432b20d)

## What type of PR is this? (check all applicable)

- [x] Feature
- [x] Bug Fix
- [ ] Documentation Update
- [ ] Code Refactor
- [ ] Performance Improvements

## How this can be tested

Tested on "3_three_zones_w_co2_capture" enabling LDS on storage resources.

## Post-approval checklist for GenX core developers
After the PR is approved

- [ ] Check that the latest changes on the target branch are incorporated, either via merge or rebase
- [ ] Remember to squash and merge if incorporating into develop

2024-10-08 17:00 UTC, gmantegna requested changes
Looks good overall, just two requests: 1. Can you please modify the relevant doc pages to reflect this change? 2. Do you have an idea of how much this increases runtime? Especially for a large case?

2024-10-31 17:20 UTC, gmantegna approved these changes
Looks good, thank you

2024-11-06 23:44 UTC, lbonaldo commented on src/write_outputs/long_duration_storage/write_opwrap_lds_stor_init.jl
> +    v_P = value.(EP[:vP])*1000
Is this multiplication intentional? Is it related to the scaling factor? If so, I think we should do something like:
```suggestion
    v_charge = value.(EP[:vCHARGE])
    v_P = value.(EP[:vP])
    if setup["ParameterScale"] == 1
        v_charge *= ModelScalingFactor
        v_P *= ModelScalingFactor
    end
```

2024-11-06 23:44 UTC, lbonaldo commented on src/write_outputs/long_duration_storage/write_opwrap_lds_stor_init.jl
> +    # error("STOP")
No longer needed...
```suggestion
```

2024-11-06 23:51 UTC, lbonaldo commented on src/write_outputs/long_duration_storage/write_opwrap_lds_stor_init.jl
> +    auxNew_Names = [Symbol("Resource"); Symbol("Zone"); [Symbol("n$t") for t in 1:T]]
In the codebase, `T` typically refers to the number of time steps read from the `demand` file (which is stored in `inputs["T"]`). If I’m correct, the T at this line represents the length of the sub-periods multiplied by their count (and can therefore be different from `inputs["T"]`). Could you please use a different name to improve code clarity?

2024-11-06 23:53 UTC, lbonaldo requested changes
Hey @federicoparolin, thanks so much for this PR! It looks great to me as well. I’ve added a few additional comments on the `write_opwrap_lds_stor_init` function, could you please take a look when you have a moment?

2024-11-18 17:14 UTC, lbonaldo approved these changes

2024-11-18 17:27 UTC, merged